version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: jhoe
      POSTGRES_PASSWORD: jhoe123
      POSTGRES_DB: animaldb
    ports:
      - "5432:5432"
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    environment:
      DATABASE_URL: postgres://jhoe:jhoe123@postgres:5432/animaldb
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
